### ISSUE TITLE
Constructor, Getters and Setters

### ISSUE THREAD

**Issue by farhadmn92** [HAWMobileSystems/sensomod-modeler#2]
idea:  to add an optional option for  implementation the constructor, getters and setters methods by SenSoMod Modeler; it would help to save more time

**Comment by JulianDoe** [comment]
The idea to generate constructors as well as getters and setters can be a real time saver. Therefor it will be implemented.

**Comment by JulianDoe** [comment]
Has been implemented with feature commit 1.0.2
