### ISSUE TITLE
non-complex return type in out-area of a sensor as a simple Java type

### ISSUE THREAD

**Issue by farhadmn92** [HAWMobileSystems/sensomod-modeler#3]
idea: to add an option for creating non-complex return type in out-area of a sensor as a simple Java type/attribute and not as a separate Java Classes.

**Comment by JulianDoe** [comment]
Primitive Data Types (according to oracle [https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html](url) ) can now be stated in atomic sensors (=virtual/physical sensors). This can be achieved as follows:

When in an Type-Area of a atomic sensor a primitive java data type is stated (c.f. first picture), than it will be added as field variable in the generate java code (cf. second picture).
![FirstPicture Obeo Designer](https://user-images.githubusercontent.com/25430219/51397285-2939f880-1b41-11e9-8115-e43d004debde.png)
![SecondPicture Java Code](https://user-images.githubusercontent.com/25430219/51397725-183db700-1b42-11e9-8f92-66f1ebd761b7.png)
